### ISSUE TITLE
WHO ANC OpenSRP Web: Location units page has no data

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-server-web#1158]
STEPS:
1. Login to https://web.anc-stage.smartregister.org/admin/location/unit
2. Click on the Location Unit page
3. Observe how there is no data. 
4. The locations unit's group also doesn't have data but after afew tries loads the unit groups.

![image](https://user-images.githubusercontent.com/61143692/197539493-8c13a356-34b7-4eb0-8569-30a0d9e3fe29.png)

**Comment by p-netm** [comment]
Related: https://github.com/opensrp/web/issues/920
In the past we have had 2 ways to load root locations on the opensrp-web:
1. filter where `location.properties.parentId` is null
2. filter based on geoLevel i.e where `location.properties.geoLevel === 0`.

While they logically imply the same thing, It just so happens they are independent and cannot be used interchangeably. Maybe we can get clarification of why/how exactly that is from opensrp support

Solution:
- ✔️  Quick fix: redeploy web app with `REACT_APP_FILTER_BY_PARENT_ID: "false"`
- Fix the uploaded locations, or sth on the api so that the locations can be filtered using `parentId` instead of `geoLevel`

**Comment by dubdabasoduba** [comment]
@p-netm the `geoLevel` check is very inconsistent hence the reason we moved to the `parentd`

The reason for the inconsistency is
- The implementors can push the locations via the API and not add the `geoLevel` since it's not a required field. 

I would advice using the parentId check instead of the `geoLevel` check.

**Comment by p-netm** [comment]
@dubdabasoduba cool, so then we do not need to do any changes on the web for the location list view. The changes will have to be done on the data or on the backend

**Comment by dubdabasoduba** [comment]
@p-netm agreed!

The current root location is wrongly configured. It is set to have a parentId `Uganda` This is wrong. 

@SebaMutuku Please update this location to remove the `parentId` in the root location. 

**Current root location payload**
```json
  {
    "type": "Feature",
    "id": "02ebbc84-5e29-4cd5-9b79-c594058923e9",
    "properties": {
      "status": "Active",
      "parentId": "Uganda",
      "name": "Uganda",
      "geographicLevel": 0,
      "version": 0
    },
    "serverVersion": 1,
    "locationTags": [
      {
        "id": 1,
        "name": "Country"
      }
    ]
  }
```

**Comment by SebaMutuku** [comment]
@dubdabasoduba @Naima-Bashir  the parent location has been updated to `{"id": "02ebbc84-5e29-4cd5-9b79-c594058923e9", "type": "Feature", "properties": {"name": "Uganda", "status": "Active", "version": 0, "geographicLevel": 0}, "locationTags": [{"id": 1, "name": "Country"}], "serverVersion": 1}` . This is the same value as what exists on preview instance

**Comment by Naima-Bashir** [comment]
Hi @SebaMutuku @dubdabasoduba , the Locations units page is still showing no data. See te image below:
![image](https://user-images.githubusercontent.com/61143692/198302327-297e4d08-71b2-423b-8cc1-acf74b7c950e.png)

**Comment by SebaMutuku** [comment]
@dubdabasoduba  do we need a restart of the stage instance?

**Comment by dubdabasoduba** [comment]
@SebaMutuku Please go ahead and make the following bug fixes

- [ ] Update the parentId to accept both `""` & `null` 
- [ ] If the param value for the `parentId` attributte is `""` or `null` the following should happen. 
    - [ ] Return all the locations with `parentId:""`
    - [ ] Return all the locations where the `parentId` is not defined i.e the location JSON does not have the `parentId`
- [ ] Write tests to check for both search parameters and response payloads 

Please review and add an LOE to this piece or work.

**Comment by SebaMutuku** [comment]
@dubdabasoduba  @Naima-Bashir I would request for two days to work on this. First day to fix the issue and corresponding dependency libraries and second day to write test. If I need more time them I will update.

**Comment by Naima-Bashir** [comment]
Hi @SebaMutuku . 
Here are my findings:
I can see data on the Locations Units Page. 
The Locations Unit Group however doesn't have any data, is this the case?
![image](https://user-images.githubusercontent.com/61143692/200760948-67744346-e9b6-48f2-aa90-4cde5d35def6.png)


Also unrelated but also related, how come we use Uganda as our stage data? @dubdabasoduba

**Comment by SebaMutuku** [comment]
@Naima-Bashir I have realized for location unit group, on clicking the button first time, it shows empty data. However, when you click another button and then click on `Location Unit Group` then it shows data.

**Comment by p-netm** [comment]
@SebaMutuku @Naima-Bashir The location unit group module issue, is fixed in https://github.com/opensrp/web/releases/tag/v2.3.3, just need to redeploy the web app.
