### ISSUE TITLE
Support rest/clients/getAll

### ISSUE THREAD

**Issue by gstuder-ona** [OpenSRP/opensrp-server-web#341]
There's an existing endpoint to get client ids ordered by server version (not sure the name?), but this endpoint is hard to use efficiently as you'd need to then get client data one-by-one afterwards, manage consistency when clients get deactivated, etc.

Also, for consistency in syncing it would be nice if every entity had a getAll.  The current rest/events/getAll endpoint does return clients, but they are not guaranteed in order (tested in reveal-esw project) and can sometimes be very far out of order, which means that ordering also has to be managed separately on the target syncing system.

Suspect it's not a huge amount of work on the API side but will save lots of code on the ETL side.

**Comment by pld** [comment]
This is blocking work on the OpenSRP to Canopy connectors, we need a way to to get the list of clients in order so that we can checkpoint our progress and restart if there is an interruption. These are endpoints that exist on the EventResource, which is why we are able to do that there. We can work around this but that will be a brittle fix, inefficient, and is significantly more work than adding the API endpoint.

Looking at the code, the implementation task for this is to add methods to [ClientResource](https://github.com/OpenSRP/opensrp-server-web/blob/master/src/main/java/org/opensrp/web/rest/ClientResource.java) that are equivalent to the

- [ ] [getAll](https://github.com/OpenSRP/opensrp-server-web/blob/master/src/main/java/org/opensrp/web/rest/EventResource.java#L305)
- [ ] [getById](https://github.com/OpenSRP/opensrp-server-web/blob/master/src/main/java/org/opensrp/web/rest/EventResource.java#L100)

methods in the [EventResource](https://github.com/OpenSRP/opensrp-server-web/blob/master/src/main/java/org/opensrp/web/rest/EventResource.java) class.

@githengi can we please assign this and add it to an upcoming milestone? The sooner the better but at the latest by the end of next week.
