### ISSUE TITLE
Improve performance of plans list endpoint

### ISSUE THREAD

**Issue by moshthepitt** [OpenSRP/opensrp-server-web#433]
The plans list endpoint's performance is starting to be problematic i.e. https://reveal-stage.smartregister.org/opensrp/rest/plans

This endpoint is used in many places in the web app, and some of these places do not need the full list of plans.  As such we would like:

~~- [ ] The performance of the page to be improved - e.g. why is it timing out and we only have a hundred or so plans? (Hopefully this item will be done first before the two below)~~
- [ ] The ability to paginate results from this page
- [ ] The ability to filter results from this page by plan status

**Comment by moshthepitt** [comment]
Just FYI, right now Reveal web stage is not usable because we cannot load plans

**Comment by githengi** [comment]
Related to https://github.com/OpenSRP/opensrp-server-web/issues/586

**Comment by githengi** [comment]
@moshthepitt when doing pagination what is the order that should be used? newest first

**Comment by moshthepitt** [comment]
@githengi I don't think we have a preference.  Maybe newest first, or whatever ordering was being done on the current /rest/plans?

**Comment by githengi** [comment]
Currently there is no ordering since no pagination is not supported @moshthepitt

**Comment by moshthepitt** [comment]
newest first then has my vote

**Comment by rehammuzzamil** [comment]
As per my understanding, we need to provide a functionality of pagination in **/rest/plans GET** endpoint.
To implement this, we need to perform **RowBounds** pagination based on OFFSET and LIMIT parameter which would define the start position and the amount of data to query.
Order by type will also be a part of PlanSearchBean which would be initialized as DESC by default (to bring new plans at the top).
A **PlanSearchBean** object will be declared which would comprise of fields like pageNumber, pageSize, orderByType, and PlanStatus. The planStatus field is used to filter the results from the page based on the given planStatus and only those rows will be displayed which matches the criteria.

Moreover, the existing request param of IS_TEMPLATE would remain as is.
For instance, if the page number param is not provided, all the records will be returned in one go to ensure backward compatibility.
Otherwise, API needs to be triggered for the next page every time.
cc: @githengi

**Comment by moshthepitt** [comment]
> For instance, if the page number param is not provided, all the records will be returned in one go to ensure backward compatibility. Otherwise, API needs to be triggered for the next page every time.

Does all mean everything in the database?  Or just the first 1000 like it is right now?

**Comment by rehammuzzamil** [comment]
Yes @moshthepitt it means the first 1000 records as it is the DEFAULT_FETCH_SIZE defined.

**Comment by Wambere** [comment]
@githengi   can we also add `useContext` filters to this endpoint? Need to be able to get all `case-riggered` plans, or all plans with `caseNum` x or even all plans with `taskGenerationStatus` false

**Comment by githengi** [comment]
@Wambere that is possible, we add a list of key:value for filtering using useContext?

**Comment by Wambere** [comment]
yes, that would work great!
