### ISSUE TITLE
RVL-1301 Add support for pagination of unpaginated  Resources

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-server-web#591]
Zambia production has hit the 1000 practitioner limit on the server and new practitioners are not showing up in the web Ui. Additionally, this is allowing users to enter duplicates because the dropdown menu that compares Keycloak usernames against the practitioner list isn't getting the entire list of practitioners. We need to update the practitioner endpoint to include pagination. More generally, we should update all endpoints to include pagination by default so that we can establish a pattern in these Reveal related APIs.

- [ ] Practitioners
- [ ] PractitionerRoles
- [ ] Organizations
- [ ] AssignedPlansAndLocations
- [ ] (Please add any more that I may have missed).

**Comment by hmakandi** [comment]
I would suggest the fix to be applied in 2 stages:

1. Extend the API limits to a figure like 5k to unblock the current issue

2. Add pagination to the APIs. There is a documented suggestion of achieving this in order to support the FE in this [ticket here]([https://github.com/OpenSRP/opensrp-web/issues/241].

**Comment by rehammuzzamil** [comment]
As per my understanding, it would have an impact on the following end-points:
```
- /rest/practitioner GET
- /rest/practitionerRole GET
- /rest/organization GET
- /assignedLocationsAndPlans/{identifier} GET
- /assignedLocationsAndPlans GET by plan Id
```

Wrt implementation, a **search bean** will be introduced with the minimum fields like pageNumber, pageSize, orderByType, orderByFieldName in all these resource classes. Additional fields like planIdentifier and organizationIdentifier will be added in AssignedLocationsAndPlansSearchBean. The request parameters are not required, to ensure backward compatibility. If order by type and order by field name parameters are not provided, it would return results according to the order by id in the descending order.

If the page number param is not provided, all the records will be returned in one go i.e. equal to the DEFAULT FETCH SIZE of 1000. Otherwise, API needs to be triggered for the next page every time.

To get all organizations end-point, only the method which returns all the organizations will be impacted, i.e. the one which filters based on locationId will remain the same as it is currently working.

cc: @githengi

**Comment by githengi** [comment]
This is correct @rehammuzzamil

**Comment by githengi** [comment]
We need to return counts for these APIs and an optional flag that controls if count is being returned
