### ISSUE TITLE
Create new ID for specific product item in an inventory

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-server-web#651]
We need a unique ID to refer to an individual product item in a service point's inventory. This is required, because the same product can be added more than once to a service point; hence, the inventoryID-productID is not enough to uniquely identify it.

**Comment by rehammuzzamil** [comment]
The server-side database stores an inventory item in a stock table against a particular service point (structure). As per the business flow, inventory can be searched based on a service point Id, and an end-point exists for this purpose `/rest/stockresource/servicePointId/{servicePointId}` which returns all the inventory items in a particular service point in response. Therefore, as per my understanding, the stockId which is returned against each item of the inventory is enough to uniquely identify the inventory item itself.

@cafootitt Since, at the implementation level, the Inventory object does not comprise of a list of products.

**Comment by cafootitt** [comment]
@rehammuzzamil Thanks! So it sounds like we can use stockID for this purpose. If it already exists, we can close this issue.

@githengi Does this sound ok with you as well?
