### ISSUE TITLE
Order locations alphabetically (A to Z) using the location name

### ISSUE THREAD

**Issue by dubdabasoduba** [OpenSRP/opensrp-server-web#720]
Locations should be sorted A to Z at each level. So sort the first geo level in alphabetical order (A to Z), then sort the 2nd geo-level by A to Z, and so on. This is similar to this command in Excel: 

<img width="512" alt="Screen Shot 2021-02-11 at 12 03 03 PM" src="https://user-images.githubusercontent.com/3488986/107634243-3bf75c80-6c37-11eb-9814-a2ea2b2d839d.png">
<img width="512" alt="Screen Shot 2021-02-11 at 12 03 10 PM" src="https://user-images.githubusercontent.com/3488986/107634236-37cb3f00-6c37-11eb-8963-0ba068dce231.png">

**Comment by rehammuzzamil** [comment]
Hi @githengi Can you please share an end-point for this?
Also, can you please briefly explain the issue related to it to fix import scripts?

**Comment by githengi** [comment]
@rehammuzzamil you need to modify the API `/hierarchy/{locationId}` on `org.opensrp.web.rest.LocationResource.generateLocationTree(String, boolean, boolean)`

You need to order the location hierarchy so that locations within the hierarchy are ordered by name

You need to modify `org.opensrp.repository.LocationRepository.findLocationWithDescendants(String, boolean)` and return location detail list ordered by `geographicLevel and then name`

**Comment by cafootitt** [comment]
PR combined with PR from 411, Sam to review before merging, then do server-web release.

**Comment by cafootitt** [comment]
QA alphabetical locations as well as quantity -optional on add inventory item page.

**Comment by cafootitt** [comment]
Closing this, and creating new issue for clean up here: https://github.com/OpenSRP/opensrp-server-web/issues/726
