### ISSUE TITLE
Bulk CSV upload failing even though web page returned a successful response

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-server-web#727]
We discovered this was due to the inventory items not being returned in the get API call due to invalid accountability end date.

**Comment by rehammuzzamil** [comment]
![image](https://user-images.githubusercontent.com/62061579/108506422-91d4a000-72da-11eb-88a0-40864d6cfe3e.png)
The root cause of this issue is the truncation of the date in the input CSV file. Editing in tools like Excel, LibreOffice truncates the year part resulting in 2-digits only which leads to the incorrect `accountability end date `computation. 
Therefore, it is unable to meet the criteria in the GET API to fetch those records whose accountability end date is greater than or equal to today. 

For example:
`"accountabilityEndDate": "0022-02-01T19:00:00.000+0000" `The accountabilityenddate was computed in this format due to the truncation of deliverydate in the sheet. Thus, it fails to meet this criteria : `s.json->>'accountabilityEndDate' >= '2021-02-19'  `in the query.

**SOLUTION:**
The solution is to check the input string of delivery date through Pattern Matching (Regex) that it should hold all 4-digits of the year. If it does not hold the complete year (in the correct format), a validation error will occur. 
This would enforce the user to add a delivery date in the correct format (Maybe through text editors or escaping the truncation by typing in '[date] into the cell. The `'` supposedly escapes automated formatting)

cc: @githengi  @cafootitt

**Comment by rehammuzzamil** [comment]
Submitted PR for review.

**Comment by cafootitt** [comment]
PR approved and Reham created release tag for it.
