### ISSUE TITLE
Update the practitioner resource to add the get practitioners via another practitioners identifier

### ISSUE THREAD

**Issue by dubdabasoduba** [OpenSRP/opensrp-server-web#769]
- [ ] Params `practitionerId` (Practitioner identifier),`practitioner-role code` e.g `"CHW"`, `"Nurse"`
- [ ] Get location/organisation practitioner
- [ ] Get all practitioner roles using the organisation id
- [ ] Filter the practitioner roles using the practitionerRole code
- [ ] Get the practitioners referenced in the renaming practitioner roles
- [ ] bundle this up in an array and return.

**Response Sample**
```
[
  {
    "identifier": "f713620c-076e-407f-98fd-ae655b3dc5ba",
    "active": true,
    "name": "Allay Allan",
    "userId": "c1d36d9a-b771-410b-959e-af2c04d132a2",
    "username": "allay_allan"
  },
  {
    "identifier": "0181207b-7752-4e58-a945-f35d0e5af7f3",
    "active": true,
    "name": "test 2",
    "userId": "894eb738-78e3-4ec8-aba1-30ae5e42622e",
    "username": "test2"
  }
]
```

**Acceptance Criteria**
- [ ] If you pass a Practitioner role `identifier` and the `practionerRole core text` the following should happen. 
- [ ] Return a list of practitioners in the same team as the practitioner in the practitioner role identifier passed
- [ ] The returned practitioners should also have the same practitionerRole core text passed in

**Comment by rehammuzzamil** [comment]
As per my investigation, steps for getting the practitioners from the identifier of the supervisor practitioner are:

- [ ] First get all the organizations (teams) in which this lead practitioner is a part. Traverse the practitioner role table and get the details of the organization.
- [ ] Based on the organization Ids retrieved in step 1, run a loop on organization Ids and get all the practitioner roles by filtering on the organization Id and Code,  the purpose for retrieving practitioner role here is to get the list of practitioner Identifiers, since this is the only linking table which provides us information of Organization and Practitioners.
- [ ] Finally, fetch all the Practitioners from the list of Practitioners Identifiers prepared above.
- [ ] The idea is to expose an end-point on PractitionerResource with request parameters of String practitionerIdentifier, String practitionerRoleCode.

@dubdabasoduba Please review. Thanks!

**Comment by dubdabasoduba** [comment]
> As per my investigation, steps for getting the practitioners from the identifier of the supervisor practitioner are:
> 
> * [ ]  First get all the organizations (teams) in which this lead practitioner is a part. Traverse the practitioner role table and get the details of the organization.
> * [ ]  Based on the organization Ids retrieved in step 1, run a loop on organization Ids and get all the practitioner roles by filtering on the organization Id and Code,  the purpose for retrieving practitioner role here is to get the list of practitioner Identifiers, since this is the only linking table which provides us information of Organization and Practitioners.
> * [ ]  Finally, fetch all the Practitioners from the list of Practitioners Identifiers prepared above.
> * [ ]  The idea is to expose an end-point on PractitionerResource with request parameters of String practitionerIdentifier, String practitionerRoleCode.
> 
> @dubdabasoduba Please review. Thanks!

lgtm

**Comment by rehammuzzamil** [comment]
**Testing Steps (Acceptance Criteria)**

**Step 1:**
Create Practitioners/Users using end-point /rest/practitioner POST
Create 4 Practitioners out of which two have the role of Community Health Worker, one has the role of Supervisor and one has a role of let's say IT.

**Step 2:**
Create team/Organization using POST /rest/organization/

**Step 3:**
Add all four practitioners to Team using /rest/practitionerRole/add/

**Step 4:**
Fetch all Community Health Workers which are managed by the supervisor.
Pass supervisor Practitioner Identifier as a Request Param and also the role code passed in the request param.

Step 5:
Observe the response of the API, there will be only two Practitioners in the response payload.

@dubdabasoduba Please correct me if there is anything wrong. Thanks!
