### ISSUE TITLE
Update the inventories endpoint

### ISSUE THREAD

**Issue by Wambere** [OpenSRP/opensrp-server-web#810]
Requesting the following changes on the inventories endpoint `[/stockresource]`
- change `/getall` to `/getAll` so it matches all the other endpoints
- add `serverVersion` parameter and return only rows with a serverVersion higher than what is passed
- add `limit` parameter and return the number of rows specified or less if at the end of batch

This would be nice for uniformity, but also required for https://github.com/onaio/canopy/issues/1873

**Comment by rehammuzzamil** [comment]
Hi @Wambere @samkanga,
Here are my investigations:
- The end-point was exposed back in `2018`.
- Renaming end-point would affect Front-end apps too and requires an update on the front-end + android apps as well (on all projects).
- I can add `serverVersion` and `limit` as Request Params (optional).
- If `limit` param value is not provided then the default fetch size (`1000`) will be used, otherwise, the number of rows will be returned on the basis of `limit` param.

Please share your thoughts on this.

**Comment by Wambere** [comment]
@rehammuzzamil that is okay for now. Please go ahead and add the two parameters

**Comment by rehammuzzamil** [comment]
> @rehammuzzamil that is okay for now. Please go ahead and add the two parameters

Sure, noted. Thanks @Wambere

**Comment by rehammuzzamil** [comment]
Provided support for String `serverVersion` and Integer `limit` **optional** request params.
If the serverVersion field is provided rows are returned with a serverVersion higher than the provided value.
If a limit parameter is provided, the number of rows is returned accordingly. If the limit param is not provided, the default number of rows (`1000`) will be returned.

Example:
`http://localhost:8080/opensrp/rest/stockresource/getall?limit=1200&serverVersion=1621003030509`

cc : @Wambere  @samkanga

**Comment by rehammuzzamil** [comment]
@Wambere  @samkanga  This issue has been completed and merged to Master. It is a part of Opensrp-server-web version `2.6.8-SNAPSHOT`
