### ISSUE TITLE
POAT point from previous plans not loading in new case-triggered plans

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-server-web#813]
https://smartregister.atlassian.net/browse/RVL-1576
When a user taps an POAT from a previous plan, they receive an error message.

Plan: A1 - เมืองทอง(Site)-1 - Test1 อภิรังษีกุล - 2021-04-26 - Site
Plan ID: `89932189-8b22-44d3-8f9a-0ef72cc0fab2`

User: test77

![image](https://user-images.githubusercontent.com/61143692/116074704-c5e18e00-a69a-11eb-8b21-cafb88eb91bf.png)

Below is the English version of the error returned.
![image](https://user-images.githubusercontent.com/5908630/116112258-11f2f980-a6c0-11eb-8e70-2f6dca89ac88.png)

**Comment by Naima-Bashir** [comment]
1. POAT should not come in pink colour 
2. When you click on a POAT, you should not get Fetch Family failed error. 
3. Loading data from previous plans is part of EP; still in progress

**Comment by Naima-Bashir** [comment]
![image](https://user-images.githubusercontent.com/61143692/116370653-475c2c00-a813-11eb-9f3c-f6a29b25e1a3.png)
![image](https://user-images.githubusercontent.com/61143692/116370672-4c20e000-a813-11eb-8210-82a942e47086.png)
![image](https://user-images.githubusercontent.com/61143692/116370688-504cfd80-a813-11eb-9f65-44849cc4bc2e.png)

Test steps:
I created a POAT in plan 1
I then switched to plan two and looked for that POAT I had created
It was in pink colour 
I clicked on it, it gave me this error- fetch family failed
@faidvd

**Comment by Naima-Bashir** [comment]
So I used test77 to create a case triggered plan for it. 
I was able to create a PAOT and register it 
That part has passed QA 
However, when I click on certain families, there are no tasks generated 
![image](https://user-images.githubusercontent.com/61143692/119316823-13dcb800-bc80-11eb-9a12-55f8df928b98.png)
cc @samkanga @Rkareko @faidvd

**Comment by Naima-Bashir** [comment]
![image](https://user-images.githubusercontent.com/61143692/119336971-f6ffaf00-bc96-11eb-9197-dfe01c2abb3c.png)
Previous PAOT, give this error: Loading Failed

**Comment by Naima-Bashir** [comment]
I have logged in using test77 and clicked on a case triggered plan- 2021-04-26
When I clicked on a previous PAOT, it have me a loading failed error.
See image below 
![image](https://user-images.githubusercontent.com/61143692/121342296-2a466d00-c92a-11eb-8a98-b6a36d5f5c14.png)
When I click on others I get the PAOT
![Uploading image.png…]()

**Comment by madrinekariuki** [comment]
POAT for case triggered plans from previous plans are not loading.
I did a follow up on this and I was informed that the fix was updating the error message popping up. refer to [this](https://smartregister.atlassian.net/browse/RVL-1576)
error showing is below.
![image](https://user-images.githubusercontent.com/84722169/124622363-b72a0b00-de83-11eb-9362-2b21cf3ce3c7.png)


screenshots
see below how the error shows on the APKS .
th-en apks (both preview and local)
![image](https://user-images.githubusercontent.com/84722169/124623294-8b5b5500-de84-11eb-91f1-cd088507872c.png)

th apks (both preview and local)
![image](https://user-images.githubusercontent.com/84722169/124623786-f4db6380-de84-11eb-9520-2a478cba3d91.png)
