### ISSUE TITLE
Add Validation on the OPenSRP Plans End Point

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-server-web#848]
The Plan Generation Processor Group in NiFi facilitates the generation of a new plan. The process starts by pulling new Case Details events from OpenSRP, using the ETL state machine PG to track state. When records are retrieved we start by checking that they have all the required fields populated. Next a query is run against the `dbo.auto_generated_plans` table to confirm that no plan has been generated for the specified event. 

If a plan already exists with the case details eventID, the flowfile is rerouted and left to 'hang' otherwise the process continues. We then confirm that a matching OpenSRP jurisdiction exists for the Biophics operational area id provided in the index case. Next step is to pick a plan template. Once the plan template is selected, the plan payload is generated and posted to the OpenSRP endpoint. Finally we update the `dbo.auto_generated_plans` table with the plan details.

In an event where there is no communication from OpenSRP at the point when the check to determine if the plan exists is being done, it creates a false impression that there is no plan for the specified events, and progresses the plan generation. We need to add a validation such that the OpenSRP Plans endpoint returns appropriate codes when OpenSRP is unavailable. The codes will then be used to determine when:

- [ ] OpenSRP is unavailable and a wait is required until OpenSRP is available
- [ ] When OpenSRP is available but no plan exists for the specified events and hence plan generation can go on.
- [ ] When OpenSRP is available and a plan exists for the specified events and so no new plan needs to be generated.

**Comment by Rkareko** [comment]
> In an event where there is no communication from OpenSRP at the point when the check to determine if the plan exists is being done, it creates a false impression that there is no plan for the specified events, and progresses the plan generation. We need to add a validation such that the OpenSRP Plans endpoint returns appropriate codes when OpenSRP is unavailable. The codes will then be used to determine when:

@samkanga @Wambere @moshthepitt which API call is used to make this check?

**Comment by Wambere** [comment]
There is no API call, the only check that is done is against the `dbo.auto_generated_plans` table

**Comment by Rkareko** [comment]
> There is no API call, the only check that is done is against the `dbo.auto_generated_plans` table

@samkanga Not clear on what is to be done on the opensrp API since the check is done on another system

**Comment by moshthepitt** [comment]
@Rkareko my hope is that when a new plan is being added OpenSRP can check if a duplicate plan already exists i.e. check if another plan with the same `opensrpEventId` useContext value already exists and then refuse to create a new plan if it does.

**Comment by moshthepitt** [comment]
In Canopy the SQL to achieve something similar to that would look like:

```sql
SELECT EXISTS (
    SELECT 1
    FROM events
    WHERE events.id IN (
        SELECT
        plans_with_context.use_context::JSONB->>'valueCodableConcept' AS case_number
        FROM (SELECT
            raw_plans.id AS id,
            jsonb_array_elements_text(raw_plans.full_json->'useContext') AS use_context
        FROM raw_plans) AS plans_with_context
        WHERE plans_with_context.use_context::JSONB->>'code' = 'opensrpEventId'
    )
   -- the event id is defined here
    AND events.id = '28e4cbec-a9d8-4490-a2f3-018528cfedce'
) AS plan_for_event_exists;
```

^^ this query might have some rough edges :)

**Comment by Rkareko** [comment]
Thanks @moshthepitt . Quick question is there a 1:1 mapping between a case triggered plan and a case details event?

**Comment by moshthepitt** [comment]
@Rkareko yes there is.  One case details event should result in one plan/

**Comment by madrinekariuki** [comment]
To confirm that a new plan is created when none exists for a given event
status response 201 showing that a new plan has been created
using anew identifier and new opensrpEventId UUIDs
![image](https://user-images.githubusercontent.com/84722169/124254974-52447d00-db32-11eb-807c-2f2f31c0ea53.png)
-Then sent a get request with the identifier to create the plan used to confirm that a new plan has been created.
https://reveal-th-preview.smartregister.org/opensrp/rest/plans/aa69b2d6-b5ce-4a4d-8913-a7b659f5e883
![image](https://user-images.githubusercontent.com/84722169/124255119-7e5ffe00-db32-11eb-92d7-ef20889df50e.png)



Testing that no new plan is created when one exists for a given event
-when you attempt to create a new plan with an existing EventID you get an error that that plan already exists
-POST url https://reveal-th-preview.smartregister.org/opensrp/rest/plans
-identifier used 9a245893-7688-4e72-b973-0856c710d533
-opensrpEventId 3931fc26-fc35-4530-898d-38d9274fe069
![image](https://user-images.githubusercontent.com/84722169/124255582-ff1efa00-db32-11eb-9ca2-bfff143dc0d0.png)
-when you do GET request for that identifier, you will see that no plan has been created because the eventID already exists thus the GET request does not return any plan
-https://reveal-th-preview.smartregister.org/opensrp/rest/plans/9a245893-7688-4e72-b973-0856c710d533
![image](https://user-images.githubusercontent.com/84722169/124255678-1b229b80-db33-11eb-8cb3-215b5512a369.png)
